### ISSUE TITLE
deployable.context not taken into account

### ISSUE THREAD

**Issue by imartinbe** [bmuschko/gradle-cargo-plugin#106]
Hi,
I have setup cargo with following closure : 
```groovy
cargo {
    containerId 'tomcat7x'
   deployable {
        context = project.name        
    }
    remote {
        hostname = tomcat_dev_host
        username = tomcat_dev_user
        password = tomcat_dev_password
    }
}
```
When deploying to tomcat 7, the context is not considered : the web app deployed is "${project.name}-war".
I can set deployable.context="blabla", it does not use it.
However for the *cargoUndeployRemote* task, the context is used... and I get 
>Execution failed for task ':MyApp:cargoUndeployRemote'.
> org.codehaus.cargo.container.ContainerException: Deployable [/blabla is not deployed

**Comment by dcominottim** [comment]
I was having the same issue with WildFly 8.2.0, but then I noticed that I was specifying a custom context in my jboss-web.xml file that is deployed within the WAR. I do not know whether Tomcat is affected by some file similar to jboss-web.xml, but it might be worth to double-check your code and XMLs.

**Comment by bmuschko** [comment]
@imartinbe Are you setting a context file?

**Comment by imartinbe** [comment]
I have some db connection settings in <tomcat_home>/conf/context.xml ... otherwise nothing...

**Comment by bmuschko** [comment]
This works fine for me with the plugin version 2.0.3 which uses 1.4.8. I'd recommend upgrading your plugin version and try again.

**Comment by bmuschko** [comment]
@imartinbe Any chance you can try this again with the suggested plugin version?

**Comment by bmuschko** [comment]
Closing this as I can't reproduce the issue and haven't heard back.
