### ISSUE TITLE
Change cargo local logFile property in README

### ISSUE THREAD

**Issue by jukkahell** [bmuschko/gradle-cargo-plugin#110]
Change this line in README:
logFile: The Cargo log file of your local container (defaults to writing to the console).

to this:
**log**: The Cargo log file of your local container (defaults to writing to the console).

**Comment by jukkahell** [comment]
It seems that I'm too busy doing this right now. My apologies...

**Comment by noroutine** [comment]
I'd appreciate if this be actually done ;) just spent half-hour before I found this issue :-D

**Comment by bmuschko** [comment]
@noroutine I am still waiting for a pull request. :-)
