### ISSUE TITLE
Support for exploded WAR deployment?

### ISSUE THREAD

**Issue by hrstoyanov** [bmuschko/gradle-cargo-plugin#115]
According to the CARGO docs, WildFly 8 exploded war  deployment (e.g. unpackaged WAR directory) is supported:
http://cargo.codehaus.org/WildFly+8.x
See "Static deployment of expanded WAR". This is very valuable and efficient feature during development. How can this be done with this plug-in? Reading the docs, it seems the deployable closure has an attribute 'file' that can only point to an archive file WAR or ERA and not a folder?

Here is my configuration:
...
cargo {
    containerId = 'wildfly8x'
    remote {
        hostname = 'localhost'
        username = 'admin'
        password = 'admin'
    }
    local {
        //jvmArgs = '-Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=n'
        homeDir = file("${wildfly_root}")
    }
    deployable {
        file = tasks.warTemplate.destinationDir
        //file = tasks.draftWar.archivePath
        context = '/draft'
    }
}

Here is what happens:
....
Executing task ':stocks4grab:s4g-web:cargoRedeployRemote' (up-to-date check took 0.011 secs) due to:
  Task.upToDateWhen is false.
Container ID = wildfly8x
Deployable artifacts = [/home/hristo/projects/peruncs/stocks4grab/stocks4grab/s4g-web/war]
Starting action 'redeploy' for remote container 'WildFly 8.x' on 'http://localhost:8080'
Container properties = [:]
Unknown deployable type: 
:stocks4grab:s4g-web:cargoRedeployRemote FAILED
:stocks4grab:s4g-web:cargoRedeployRemote (Thread[main,5,main]) completed. Took 0.399 secs.

Thanks.

**Comment by jechlin** [comment]
Hi Benjamin. Thanks for this great plugin. Just wanted to add my support to this request, in my case pointing tomcat to an exploded war file.

**Comment by bmuschko** [comment]
@jechlin I am not sure if that's supported for Tomcat with Cargo. Something to try out. OK, guys...I am waiting for the pull request. :-)

**Comment by jechlin** [comment]
@bmuschko I don't know much about cargo to be honest, although http://cargo.codehaus.org/Static+deployment+of+expanded+WAR indicates it's possible I think... 
I would love to have a go at making the changes. When I get time I'll have a punt, but no idea when that will be.

**Comment by jianliao** [comment]
Hi @bmuschko, A pull request - https://github.com/bmuschko/gradle-cargo-plugin/pull/120 for this feature had been sent. Could you please review?

**Comment by bmuschko** [comment]
@jianliao Did you see my comment on your pull request?

**Comment by hrstoyanov** [comment]
This is such an important issue ...4 months now. I see if I can help tonite.

/Hristo Stoyanov
