### ISSUE TITLE
Setting JMX properties on tomcat makes it not possible to stopCargoLocal

### ISSUE THREAD

**Issue by dudadornelles** [bmuschko/gradle-cargo-plugin#118]
Hey,

I have the following config
```groovy
local {
    sytemProperties {
        property 'com.sun.management.jmxremote.ssl', 'false',
        property 'com.sun.management.jmxremote.authenticate', 'false',
        property 'com.sun.management.jmxremote.ssl', 26000
    }
}
```

When starting Tomcat everything works fine but when stopping it tries to start JMX one more time and Tomcat gets stuck. Any ideas on what to do to fix that?

Thank you!

**Comment by dudadornelles** [comment]
Just adding something - I understand this options should be set on CATALINA_OPTS and not on a system wide way, since if it is system wide it will be used in both the start and stop process. I just don't know exactly how to do this with cargo.

**Comment by bmuschko** [comment]
You probably only want to set the system properties when starting the container and not when stopping it. Something like this should do:

    tasks.withType(CargoStartLocal) {
        systemProperties = ['com.sun.management.jmxremote.ssl': 'false',
                            'com.sun.management.jmxremote.authenticate': 'false',
                            'com.sun.management.jmxremote.ssl', 26000]
    }

**Comment by dudadornelles** [comment]
That did the trick, just small things:

- For some reason I had to add the full path for CargoStartLocal: com.bmuschko.gradke.cargo.tasks.local.CargoStartLocal
- "typo" in the last line: `'com.sun.management.jmxremote.ssl', 26000` -> `'com.sun.management.jmxremote.ssl': 26000`

Thanks a lot!

Duda

**Comment by bmuschko** [comment]
Correct, you'll need to import the custom task type.
