### ISSUE TITLE
Does this plugin support JBoss AS?

### ISSUE THREAD

**Issue by xianlinbox** [bmuschko/gradle-cargo-plugin#12]
Hi Guys

```
I want to deploy my application to the JBoss AS? Does this plugin support it?
```

Best Regards
Shining

**Comment by Rajagor** [comment]
@bmuschko I am trying to work with JBoss7, EAR local deployment with Gradle. I have used the JBoss6 Example provided above. Am not able to get it to work. Am new to build tool, can you please help me.
Also, am not able to access  http://cargo.codehaus.org/. Can you suggest any site to check the containerID and any related stuff? Thank you

**Comment by Rajagor** [comment]
@bmuschko Can you please help with the sample build script for JBoss 7

**Comment by bmuschko** [comment]
@Rajagor It likely looks very similar to the one above except that you'd set a different container ID. Maybe sure to use the latest version of the plugin.

```
cargo {
    containerId = 'jboss7x'
    ...
}
```
