### ISSUE TITLE
Wildfly deployment

### ISSUE THREAD

**Issue by IsraelEndale** [bmuschko/gradle-cargo-plugin#127]
Gets a message 'Failed to create a WildFly 8.x standalone configuration' trying to deploy.

My gradle build is as follows:

apply plugin: "war"
apply plugin: 'com.bmuschko.cargo'
description = ''

sourceCompatibility = 1.8

buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        jcenter()
    }
    dependencies {
        classpath 'com.bmuschko:gradle-cargo-plugin:2.1.1'
    }
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.11'
    providedCompile group: 'javax', name: 'javaee-api', version: '7.0'
    providedRuntime group: 'org.jboss.spec', name: 'jboss-javaee-7.0', version: '1.0.3.Final'
}

cargo {
    containerId = 'wildfly8x'
    port = 9990

    deployable {
        context = 'gercweb'
//        file = file('/Volumes/sd01s1/_Projects/xxx

    remote {
        hostname = 'localhost'
        username = 'admin'
        password = 'adminadmin'
    }

    local {
        homeDir = file('/Volumes/sd01s1/_Projects/com.xxx/deployments')
        outputFile = file('build/output.log')
        timeout = 60000

        containerProperties {
//            property 'cargo.tomcat.ajp.port', 9099
        }
    }

}

**Comment by bmuschko** [comment]
see Issues #78
