### ISSUE TITLE
How to specify existing container

### ISSUE THREAD

**Issue by mrsachindixit** [bmuschko/gradle-cargo-plugin#132]
Hi ,
I am writing a script to deploy a WAR  on web sphere application server 8.5 .
When I user the startlocal task it creates a new  WAS profile and deploys the application there . 
However ,I want to reuse an existing WAS8.5 profile when i use my script.

I understand , from cargo documentation that there is a a way to specify existing profile to javacode/antscript ,But I am not able to specify this using gradle plugin : 

"Existing Local Configuration for installed container
should have a property like 
<container>
            <type>existing</type>"

The core part of of my script is as below .

    cargo {
    containerId = 'websphere85x'
    port = 9060

    
    deployable {
        file = file('D:/EAR/App.ear')
    }
    local {
         homeDir = file('C:/Program Files/IBM/WebSphere/AppServer')
         outputFile = file('output.log')
        containerProperties {
	     property 'cargo.websphere.administrator.user', 'was_admin'
	     property 'cargo.websphere.administrator.password', 'password'
	     property 'cargo.websphere.profile', 'new-profile'
	     property 'cargo.websphere.server', 'server1'
      }
    }

**Comment by bmuschko** [comment]
I never used Websphere so I don't really know what a profile is in that context. You might want to ask about this on the Cargo user list. This plugin is just a wrapper around their Ant tasks.

**Comment by bmuschko** [comment]
Closing the issue as I haven't heard back from you.

**Comment by mrsachindixit** [comment]
Thanks
