### ISSUE TITLE
Cargo local server jvmArgs (starting server in debugging mode)

### ISSUE THREAD

**Issue by dalibor983** [bmuschko/gradle-cargo-plugin#136]
In my local server configuration I set jvmArgs property to start server in debugging mode:
```
jvmArgs = "-agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n"
```
But this java arguments are applied on both tasks "cargoStartLocal" and "cargoStopLocal" and on stopping server I got something like this:
```
[INFO] [talledLocalContainer] FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
[WARNING] [talledLocalContainer] ERROR: transport error 202: bind failed: Address already in use
[WARNING] [talledLocalContainer] ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
[WARNING] [talledLocalContainer] JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [../../../src/share/back/debugInit.c:741]
```
because port 8787 is already used when server is started.

Is there any way to apply java arguments only when server is started.

**Comment by bmuschko** [comment]
Same issue as #99. Would you be interested in providing a pull request for this?

**Comment by bmuschko** [comment]
I am going to close this issue as duplicate.
