### ISSUE TITLE
Lazy evalution of custom deploy

### ISSUE THREAD

**Issue by mofus** [bmuschko/gradle-cargo-plugin#137]
Is it possible to create a custom deploy task that is lazily evaluated?

```
task deploy(type: CargoRedeployRemote) << {
    def hostInput = "$host"
    def passwordInput = "$pass"
    def projektInput = "$modul"

    def context = projektInput.toLowerCase()
    def modulNavn = context.capitalize()

    containerId = 'tomcat7x'
    hostname = hostInput
    username = 'tomcat'
    password = passwordInput
}
```

If I add the ```<<``` I get these errors when I run my deploy task
```
> No value has been specified for property 'containerId'.
> No value has been specified for property 'username'.
> No value has been specified for property 'password'.
```

What I want to achieve is to either provide these arguments on the command line or create another task which asks the user for input.

**Comment by bmuschko** [comment]
You are assigning the property values during the execution phase which is too late to configure the task. You can provide these arguments as project or system properties on the command line and parse them from the build script. You won't need the `<<`.

**Comment by mofus** [comment]
Thank you for the answer, much appreciated!
