### ISSUE TITLE
How to add jars to the server's lib directory

### ISSUE THREAD

**Issue by farrukhnajmi** [bmuschko/gradle-cargo-plugin#139]
I am using the cargoStartLocal task to deploy an ear module to a JBoss 5.1.x container.
My cargo config looks like this:

cargo {
    containerId = 'jboss51x'
    
    local {
        homeDir = file(jbossHome)
        configHomeDir = file(jbossHome+"/server/test")
    }
}

This creates a jbossHome/server/test folder tree with an empty jbossHome/server/test/lib directory.

I would like to know how I can add a jar to this folder during the cargoStartLocal  task.

Perhaps this would be a good addition to the FAQ. Also, consider moving the FAQ entries to the wiki at https://github.com/bmuschko/gradle-cargo-plugin/wiki so user community can contribute content.

Thanks for a great plugin.

**Comment by bmuschko** [comment]
This is documented as Groovydocs. The custom task type is directly linked on the README page. Please have a look at the property `sharedClasspath ` in [LocalCargoContainerTask](http://bmuschko.github.io/gradle-cargo-plugin/docs/groovydoc/com/bmuschko/gradle/cargo/tasks/local/LocalCargoContainerTask.html).

**Comment by bmuschko** [comment]
I haven't heard back from you in the meantime. I am closing the issue. Feel free to reopen the issue if you need further assistance.
