### ISSUE TITLE
Http Basic Authentication

### ISSUE THREAD

**Issue by fast4ward** [bmuschko/gradle-cargo-plugin#142]
Is it possible to deploy to a remote tomcat manager with an additional http basic authentication in front?

I've got a test system which is generally protected by a reverse proxy, which itself required basic authentication. The configured username and password are used for tomcat manager, so how do I configure authentication for the connection?

**Comment by bmuschko** [comment]
I think that would be a better question for the Cargo user mailing list. If Cargo supports it then the plugin can. It's really just a wrapper around the Cargo Ant task.

I am going to close the issue here.
