### ISSUE TITLE
Could not find method cargo() 

### ISSUE THREAD

**Issue by nareshvatsal39** [bmuschko/gradle-cargo-plugin#143]
I am using gradle 2.8.I am getting below error
C:\Users\naresh.vatsal\workspace_spring_jan14\SpringMvcUsingGradle>gradle clean build

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\naresh.vatsal\workspace_spring_jan14\SpringMvcUsingGradle\build.gradle' line: 49

* What went wrong:
A problem occurred evaluating root project 'SpringMvcUsingGradle'.
> Could not find method cargo() for arguments [build_3gitu3al50b7kv8zi1ebj3qsr$_run_closure3@738c2576] on root project 'SpringMvcUsingGradle'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'war'
apply plugin: 'com.bmuschko.tomcat-base'
apply plugin: 'com.bmuschko.cargo-base'
ext.tomcatVersion = '7.0.67'

sourceCompatibility = 1.7

buildscript
{
   
   repositories {
  			  maven{
      				url "https://plugins.grdev.net/m2/"
      				

          			}
                 }
   dependencies {
   				 classpath "com.bmuschko:gradle-tomcat-plugin:2.2.4"
    			 classpath 'com.bmuschko:gradle-cargo-plugin:2.2'
                 }
 }
 repositories {
  mavenCentral()
 }
   
   
 dependencies 
 { 
         
    def cargoVersion = '1.4.5'
    cargo "org.codehaus.cargo:cargo-core-uberjar:$cargoVersion",
          "org.codehaus.cargo:cargo-ant:$cargoVersion"
    compile 'org.springframework:spring-context:4.0.0.RELEASE'
    compile 'org.springframework:spring-webmvc:4.0.0.RELEASE'
    compile 'org.aspectj:aspectjrt:1.7.4'
    compile 'javax.inject:javax.inject:1'
    compile 'javax.servlet:jstl:1.2'
    compile 'org.slf4j:slf4j-api:1.7.5'
    compile 'org.slf4j:jcl-over-slf4j:1.7.5'
    compile 'org.slf4j:slf4j-log4j12:1.7.5'
    compile 'log4j:log4j:1.2.15'
     testCompile 'junit:junit:4.7' 
}

cargo
 {
    containerId = 'tomcat7x'
    port = 8080
 
    local {
        homeDir = file('C:/mdi/soft/apache-tomcat-7.0.67')
        output = file('C:/mdi/soft/apache-tomcat-7.0.67/output.log')
          }
}
war 
{   
    version = '' 
 }

**Comment by bmuschko** [comment]
You will need to apply the plugin `com.bmuschko.cargo`. The base plugin doesn't have any knowledge of the `cargo` extension.
