### ISSUE TITLE
allow to specify when outputs are up to date

### ISSUE THREAD

**Issue by janbols** [bmuschko/gradle-cargo-plugin#146]
I'm calling `cargoStartLocal` before running my `integrationTest` and `cargoStopLocal` afterwards. However when `integrationTest` is UP-TO-DATE, I don't want to call `cargoStartLocal` or `cargoStopLocal`.

Currently, I don't know of any reasonable way to do that because every cargo task specifies it's never upToDate (see https://github.com/bmuschko/gradle-cargo-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/cargo/tasks/AbstractCargoContainerTask.groovy#L83), and I didn't find a way to overwrite this behaviour.

**Comment by bmuschko** [comment]
This is rather a general Gradle question and not really related to the plugin. Could you please ask the question on the [Gradle forum](https://discuss.gradle.org/)?

**Comment by janbols** [comment]
Well, it's not really a general problem. The problem is that the `cargoStartLocal` task explicitly states that it should never be up-to-date and there's no way to override that configuration.

Anyway, I raised the same issue on the gradle forum like you asked (https://discuss.gradle.org/t/how-to-override-uptodate-behaviour-cargostartlocal/15122). I didn't receive any replies yet, but let's wait and see.
Jan

**Comment by bmuschko** [comment]
You can just override [this behavior](https://github.com/bmuschko/gradle-cargo-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/cargo/tasks/AbstractCargoContainerTask.groovy#L82) and inject the behavior you'd like e.g. with the following `<taskName>.outputs.upToDateWhen { ... }`.

**Comment by janbols** [comment]
No, I don't think so. That would be too easy :smile:. 

`outputs.upToDateWhen { ... }` internally adds a `Spec` to an `org.gradle.api.specs.AndSpec`. When I configure it again by specifying `cargoStartLocal.outputs.upToDateWhen{true}`, it will simply add an extra `Spec` to the `AndSpec` but will not overwrite the original one. 

Upon evaluation, `AndSpec#isSatisfiedBy` will return false at the first `Spec` it finds. This will be the one that is added in `AbstractCargoContainerTask`.

**Comment by bmuschko** [comment]
In that case you might want to play around with an `onlyIf` statement.

**Comment by janbols** [comment]
Unfortunately that didn't work. However someone on the gradle forum did provide a working solution (see https://discuss.gradle.org/t/how-to-check-if-a-future-task-is-up-to-date/15189/4).

Greetings
Jan
