### ISSUE TITLE
Cargo gradle plug-in future?

### ISSUE THREAD

**Issue by hrstoyanov** [bmuschko/gradle-cargo-plugin#148]
First, let me shout out to Benjamin, for the awesome job of maintaining this plug-in so far! I critically depend on it and use it with no issues! 

Going forward, I totally understand why one can get busy and solicit help from  the community as Benjamin did. 

I have two questions:

1  In the short term,  is it possible to squeeze is some time and register this plug-in with the Gradle portal? This would lead to even more compact usage code like, basically just this:

```
plugins {
    id 'com.bmuschko:gradle-cargo-plugin:2.2.2'
}
```
See:
https://plugins.gradle.org/docs/submit
http://gradle.org/blog/new-gradle-plugin-portal/

2  How much work would be needed to re-write this plug-in in Java completely? For me, Groovy is the biggest impediment to submitting code PRs, as the language is not very popular these days. There are plenty of Java gradle plug-ins sample code out there to start with...

Thanks.

**Comment by hrstoyanov** [comment]
Just noticed in the Gradle 2.14-RC 1release notes that converting plugins from Groovy to Java is a trend now at Gradle:
https://docs.gradle.org/release-candidate/release-notes#a-number-of-plugins-were-converted-from-groovy-to-java

**Comment by bmuschko** [comment]
1) The plugin is [already available](https://plugins.gradle.org/plugin/com.bmuschko.cargo) through the portal.
2) The main reason Gradle core is switching from Groovy to Java is improve runtime performance. The Cargo plugin would only be applied to projects applying the WAR or EAR plugin. Therefore, the impact should be low. I am personally not planning to convert the plugin to Java. If a contributor wants to run with it, please go ahead. Optimally, that person would also continue to own the development of the plugin.

**Comment by bmuschko** [comment]
I am going to close this issue. If somebody wants to rewrite the plugin to Java, please open a pull request.
