### ISSUE TITLE
the tomcat localhost.log is missing

### ISSUE THREAD

**Issue by rlagoue** [bmuschko/gradle-cargo-plugin#153]
Sorry I was not notified about your answer. 
Here are my configurations 
`cargo {
    containerId =  "${rootProject.cargoContainerId}"
    local {
        homeDir     = file(cargoHome)
        configHomeDir   = file(cargoHome)
        outputFile = file('build/containerOutput.log')
        logFile = file('build/containerOutput.log')
        logLevel = 'low'
        sharedClasspath = files(configurations.postgresJdbc.resolvedConfiguration.resolvedArtifacts*.file)
        ...
}
}`

The problem is that unexpected exceptions stacktrace are not printed out in any cargo output log files. When I use the war generated by my application during the gradle build in a normal tomcat installation, I can see the stack trace in the file <TOMCAT_HOME>/logs/localhost.<timestamp>.log

It is a little bit annoying since I have to check it  in a normal tomcat installation everytime I get into troubles

Thank you

Here is a screenshot of the gradle script file
![image](https://cloud.githubusercontent.com/assets/5127870/15985916/f4bf0c0e-2ffb-11e6-8e52-1e4960789b06.png)

**Comment by bmuschko** [comment]
What kind of logging are we talking about (that is not found in the log files), System out/err or something that comes from a logging framework? What logging framework are you using?

Keep in mind that this plugin only calls off to the [Cargo Ant tasks](https://codehaus-cargo.github.io/cargo/Ant+support.html). It's likely an issue with either Cargo itself or the Ant integration of Gradle core. Can you provide a simplistic example project that demonstrates the issue?

**Comment by rlagoue** [comment]
Hi Benjamin,

Thank you for your answer. I am speaking about the log for the virtual host within tomcat (the localhost-<dateTime>.log) . Usually there's not much of interest in it, but when you cannot find an error in catalina.out and something is seriously wrong, this file should be checked.

In ongoing development the coder needs sometime have to take the war file generated by gradle and put it in a standalone tomcat installation, in order to understand why the application does not start using the gradle-cargo-plugin. 

Cheers

**Comment by bmuschko** [comment]
For that I'd like to refer you to the [Cargo mailing list](https://groups.google.com/forum/#!forum/codehaus-cargo) as that functionality is implemented by Cargo. Please ask the question over there. Let me know if a newer version of Cargo does implemented this functionality.

**Comment by rlagoue** [comment]
ok.. I will check this out
