### ISSUE TITLE
proper way to specify `containerProperties` once using `com.bmuschko.gradle.cargo.tasks.remote.CargoDeployRemote`

### ISSUE THREAD

**Issue by typekpb** [bmuschko/gradle-cargo-plugin#155]
What is the proper way to use `containerProperties` with `com.bmuschko.gradle.cargo.tasks.remote.CargoDeployRemote` ?

I've tried:

	class RemoteContainer {
	    String name
	    String hostname
	    Integer port
	    String username
	    String password
	}

	def remoteContainers = [new RemoteContainer(name: 'tomcat1', hostname: 'remote-tomcat1',
		                                    port: 9090, username: 'admin', password: 's3cr3t'),
		                new RemoteContainer(name: 'tomcat2', hostname: 'remote-tomcat2',
		                                    port: 8050, username: 'deployer', password: 'qwerty'),
		                new RemoteContainer(name: 'tomcat3', hostname: 'remote-tomcat3',
		                                    port: 8888, username: 'su', password: 'powerful')]

	apply plugin: 'com.bmuschko.cargo-base'

	remoteContainers.each { config ->
	    task "deployRemote${config.name.capitalize()}"(type: com.bmuschko.gradle.cargo.tasks.remote.CargoDeployRemote) {
		description = "Deploys WAR to remote Tomcat '${config.name}'."
		containerId = 'tomcat7x'
		hostname = config.hostname
		port = config.port
		username = config.username
		password = config.password

		containerProperties {
			property 'cargo.tomcat.ajp.port', 9099
		}
	    }
	}

but then I get error similar to:

    Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method containerProperties() for arguments [build_bwxlc06pgbgaew04g4vot7lgg$_run_closure1$_closure14$_closure33$_closure34@6b30e6cd] on task ...

**Comment by bmuschko** [comment]
You usually configure container properties via the [extension](https://github.com/bmuschko/gradle-cargo-plugin#extension-properties). As an example:

    cargo {
         remote {
             containerProperties {
                 property 'cargo.tomcat.ajp.port', 9099
             }
         }
    }

Alternatively, you can set the properties via the field [containerProperties](https://github.com/bmuschko/gradle-cargo-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/cargo/tasks/AbstractCargoContainerTask.groovy#L76) of the task. The type is a `Map` and not a `Closure` as you used. So in your example that would be...

    task "deployRemote${config.name.capitalize()}"(type: com.bmuschko.gradle.cargo.tasks.remote.CargoDeployRemote) {
        containerProperties['cargo.tomcat.ajp.port'] = 9099
    }

**Comment by typekpb** [comment]
works, thanks!
