### ISSUE TITLE
Can't get plugin to load in gradle project

### ISSUE THREAD

**Issue by crichey** [bmuschko/gradle-cargo-plugin#159]
0
down vote
favorite
I have the following in my build.gradle:

buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'http://dl.bintray.com/content/noamt/gradle-plugins' }

    }
    dependencies {
        classpath 'com.bmuschko:gradle-cargo-plugin:2.2.3'
    }
}

plugins {
    id "com.moowork.gulp" version "0.13"
    id "com.moowork.node" version "0.13"
//    id "com.bmuschko.cargo" version "2.2.1"
}
apply plugin: 'com.bmuschko.cargo'

However, when I try to run a cargo task I get the following error:
Cannot resolve external dependency org.codehaus.cargo:cargo-core-uberjar:1.4.15 because no repositories are defined.

**Comment by bmuschko** [comment]
You will need to define a repository on the top-level of your build script. Within the `buildscript` block is not good enough. It only tells Gradle to add the plugin to the build script's classpath and where it should come from. BTW: there's no need to define all of the repos you have in the list. Just pick one that has the plugin.
