### ISSUE TITLE
Deployable doesn't exist

### ISSUE THREAD

**Issue by jeusdi** [bmuschko/gradle-cargo-plugin#161]
I'm getting this message when I perform my deploy task:

> Execution failed for task ':deployDevWildfly10'.
> Deployable ...\commty\build\libs\commty-dev-a2e81e2-dirty.war does not exist

As you can see it's trying to pick the artifact from `build\libs`.

Nevertheless, `:deployDevWildfly10` is a custom made `CargoDeployRemote` task type:

```
remoteContainers.each { config ->
	task "deployDev${config.name.capitalize()}"(type: com.bmuschko.gradle.cargo.tasks.remote.CargoDeployRemote) {
		description = "Deploys WAR to remote Web Application Server: '${config.name}'."
		containerId = config.container
		hostname = config.hostname
		port = config.port
		username = config.username
		password = config.password
		context = "webapi"
		dependsOn = [createDevelopmentWar]
	}
}
```

As you can see it depends on `createDevelopmentWar` (a custom made `War` task type):
```
task createDevelopmentWar(type: War, dependsOn: classes) {
    archiveName "commty-dev-${versioning.info.display}.war"
    destinationDir = file("$buildDir/dist")
    webInf {
	    from('scopes') {
	    	include 'configuration.development.properties'
	    	rename('configuration.development.properties', 'scope.properties')
	    	into('classes/')
	    }
	}
}
```

As you can see, I set `destinationDir` to `file("$buildDir/dist")`. So, the artifact is going to be generated in `build\dist` instead of in `build\libs`. Is there anyway to change this behaviour?

It works if I delete `archiveName` and `destinationDir` parameters from custom made war task:
```
task createDevelopmentWar(type: War, dependsOn: classes) {
    webInf {
	    from('scopes') {
	    	include 'configuration.development.properties'
	    	rename('configuration.development.properties', 'scope.properties')
	    	into('classes/')
	    }
	}
}
```

**Comment by bmuschko** [comment]
By default the base plugin already assigns a specific WAR file. You can to reconfigure the task and assign a different "deployable".

```
remoteContainers.each { config ->
    task "deployDev${config.name.capitalize()}"(type: com.bmuschko.gradle.cargo.tasks.remote.CargoDeployRemote) {
    ...
    dependsOn = [createDevelopmentWar]
    deployables = [new com.bmuschko.gradle.cargo.convention.Deployable(file: createDevelopmentWar.archivePath)]
}
```

The key to understanding _what_ and _how_ you can do it is to check the [Javadocs for the task type](http://bmuschko.github.io/gradle-cargo-plugin/docs/groovydoc/com/bmuschko/gradle/cargo/tasks/remote/CargoDeployRemote.html). Please make sure to explore before opening an issue.
