### ISSUE TITLE
How to build the war automatically before deployment?

### ISSUE THREAD

**Issue by perqin** [bmuschko/gradle-cargo-plugin#163]
If executing task "cargoRunLocal" without running task "build", the deployment fails, complaining for not finding war file. So how to build automatically before deployment? Should I use "dependsOn", or are there any configurations for it?

**Comment by bmuschko** [comment]
Yes, correct. The reason there's not an automatic task dependency is that you can deploy other artifacts not necessarily created by the project. In fact the [FAQ does make the exact statement about your question](https://github.com/bmuschko/gradle-cargo-plugin#faq).
