### ISSUE TITLE
On setting the `cargo` directory

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-cargo-plugin#167]
Hey Ben. We use this plugin to standup a tomcat instance as part of our gradle build. We'd ideally like the generated `/tmp/cargo` directory to be instead created at `<project-dir>/build/cargo` but can't seem to find the right config/property to do so. Any ideas?

**Comment by bmuschko** [comment]
I looked through the Cargo Ant documentation and it seems like there's no way you can change. Maybe you can [double-check](https://codehaus-cargo.github.io/cargo/Ant+support.html). If it is available then we can expose a property for it.

**Comment by cdancy** [comment]
Looks like [THIS](https://github.com/codehaus-cargo/cargo/blob/b0a2b20b71ad934a867c2c8184f7a7424c600947/core/api/util/src/main/java/org/codehaus/cargo/util/DefaultFileHandler.java#L579) is where they are creating the directory path. Maybe just passing along `java.io.tmpdir` as a systemProperty would work?

**Comment by bmuschko** [comment]
I guess it would work but what a hack. ;-) Plus anything that's created in the tmp dir will end up under `build`. Likely not what you'll want. Maybe you can just request the feature on the Cargo list.

**Comment by cdancy** [comment]
Yeah didn't work anyway. Tried even setting the jvmargs but still nothing. Oh well ... maybe I'll open up a PR with cargo.

**Comment by bmuschko** [comment]
You'd probably have to set the system property in your Gradle start script. I am going to close this for now. We can reopen when Cargo adds the feature.

**Comment by cdancy** [comment]
Yeah thought about that as well but that would definitely be a BIG nono for us :)
