### ISSUE TITLE
cargoRedeployRemote to Tomcat8 works but fails to update version number

### ISSUE THREAD

**Issue by foriegnbody** [bmuschko/gradle-cargo-plugin#168]
If I manually deploy a file "TPCC##1.1.0.war" it shows up in tomcat as expected as context of tpcc and a version of 1.1.0. 

However that doesn't see to be the case using cargoRedeployRemote.
It deploys, just the version is left as "None specified"

Here's the cargo snippet:

version '##' + passedVersion
//cargo config
cargo {
    containerId = 'tomcat8x'
    port = 80

    deployable {
        file = file("$buildDir/libs/TPCC" + project.version + ".war")
        context = 'tpcc'
    }

Any thoughts?

**Comment by bmuschko** [comment]
The issue you seeing is very likely a problem with the Cargo library. I have a couple of comments about your code and the approach.

I'd use the full path to the WAR archive when assigning the value. That will always give you the right path without having to manually construct it (assuming you don't do any other customizations).

```
deployable {
    file = war.archivePath
}
```

In Java, a filename usually separates the name of the artifact from the version with a dash character. It's likely that `##` cannot be recognized by Cargo. I'd use `tpcc-1.1.0.war` instead. If you can't resolve the issue by changing the artifact name then I'd ask on the Cargo mailing list.

**Comment by bmuschko** [comment]
I am going to close this issue as the conversation stopped after my suggestion.
