### ISSUE TITLE
Add Option To Set File Mode On Copied Files

### ISSUE THREAD

**Issue by opticyclic** [bmuschko/gradle-cargo-plugin#172]
I need to set some environment variables using the `setenv.sh` file in Tomcat.

However, even when the original file is executable, the copied file is not.

The `file` closure in the `local` closure should take a `fileMode` property.

**Comment by bmuschko** [comment]
The underlying Cargo Ant task currently doesn't support setting a file mode. See the [reference](https://codehaus-cargo.github.io/cargo/Ant+Tasks+Reference+Guide.html) for more information. I suggest you request the feature on their mailing list.

**Comment by bmuschko** [comment]
This has to be requested with the Cargo project. I am going to close the issue. Let me know when it is available there.
