### ISSUE TITLE
Replace org.ajoberstar with newer replacement plugin

### ISSUE THREAD

**Issue by jutoft** [bmuschko/gradle-cargo-plugin#184]
replace org.ajoberstar.github-pages with org.ajoberstar.git-publish.
The build asks all developers to do so at each build.

**Comment by bmuschko** [comment]
Happy to bring that in. In the past I had issues with other plugin that didn't play well with the underlying Git plugin - especially the `gradle-bintray-plugin`. So we have to make sure they still work together.
