### ISSUE TITLE
Gradle 6.0 and NoSuchMethodError getAssembledReader [related to cargo bug 1482]

### ISSUE THREAD

**Issue by ulk200** [bmuschko/gradle-cargo-plugin#196]
I tried to update Gradle to 6.0 and got the following exception when trying to run Tomcat

`java.lang.NoSuchMethodError: org.apache.tools.ant.filters.util.ChainReaderHelper.getAssembledReader()Ljava/io/Reader;`

I think this is because the Ant version that comes with Gradle 6.0 has been updated to 1.10.7
because this error is exactly what is described here https://codehaus-cargo.atlassian.net/browse/CARGO-1482

Updating the cargo dependency of gradle-cargo-plugin to 1.7.4 may fix the issue ? (I can't test it at the moment)
Thx

**Comment by bmuschko** [comment]
You might be right. Feel free to try it out and send a pull request for this. I will most certainly not get around to doing it in the near future.

**Comment by ulk200** [comment]
Here is a patch that fixes the issue for me, i took the oportunity to update to Gradle 6.0 to make the tests fail (same bug as i experienced on my tomcat) then i fixed it by updating the dependency version
[gradle60_fixcargo1482.patch.txt](https://github.com/bmuschko/gradle-cargo-plugin/files/3869749/gradle60_fixcargo1482.patch.txt)

**Comment by bmuschko** [comment]
Please provide the change as pull request so we can review it and have a track record for other users.

**Comment by ulk200** [comment]
FYI this is my very first Pull Request on GitHub (!)
