### ISSUE TITLE
Plugin with id 'cargo' not found - gradle 1.2

### ISSUE THREAD

**Issue by zacharycarter** [bmuschko/gradle-cargo-plugin#24]
Hello,

Using the following build.gradle file -

``` groovy
apply plugin: 'cargo'

repositories {
    mavenCentral()
}

buildscript {
    repositories {
        add(new org.apache.ivy.plugins.resolver.URLResolver()) {
            name = 'GitHub'
            addArtifactPattern 'http://cloud.github.com/downloads/[organisation]/[module]/[module]-[revision].[ext]'
        }
    }    
    dependencies {
        classpath 'bmuschko:gradle-cargo-plugin:0.3'
    }
}

cargo {
    containerId = 'tomcat6x'
    port = 8080
    context = "mycontext"
    remote {
        hostname = "192.168.1.101"
        username = "tomcat"
        password = "tomcat"
    }
}

dependencies {
    providedCompile 'javax.servlet:servlet-api:2.5'
    cargo 'org.codehaus.cargo:cargo-core-uberjar:1.1.1',
          'org.codehaus.cargo:cargo-ant:1.1.1',
          'jaxen:jaxen:1.1.1'
}
```

I'm unable to execute the gradle tasks command.

I recieve an error stating that the Plugin with id 'cargo' cannot be found.

I'm using gradle version 1.2

Any ideas?

Thank you,

-Zach

**Comment by mrsachindixit** [comment]
Not sure if it my naivety with the interpretation of the documentation. I tired my first gradle cargo script for tomcat but we kept running into "Could not find method cargo() for arguments" or "Plugin with id 'cargo' not found" . This was because we were using apply plugin: 'com.bmuschko.cargo'.
After reading this thread I modified it to apply plugin: com.bmuschko.gradle.cargo.CargoPlugin
and it has started working .Thanks .

**Comment by mrsachindixit** [comment]
@bmuschko  please help me .

**Comment by mrsachindixit** [comment]
Ran the script with --debug : 
n-memory dependency metadata cache closed. Repos cached: 1, cache instances: 1,
modules served from cache: 0, artifacts: 0

C:\Users\sachin_dixit03\Desktop\temp>gradle --debug >dbg
14:02:35.482 [ERROR] [org.gradle.BuildExceptionReporter]
14:02:35.485 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed w
ith an exception.
14:02:35.487 [ERROR] [org.gradle.BuildExceptionReporter]
14:02:35.487 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
14:02:35.488 [ERROR] [org.gradle.BuildExceptionReporter] Build file 'C:\Users\sa
chin_dixit03\Desktop\temp\build.gradle' line: 29
14:02:35.488 [ERROR] [org.gradle.BuildExceptionReporter]
14:02:35.489 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
14:02:35.489 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred eval
uating root project 'temp'.
14:02:35.490 [ERROR] [org.gradle.BuildExceptionReporter] > Could not find method
 cargo() for arguments [org.codehaus.cargo:cargo-core-uberjar:1.4.15, org.codeha
us.cargo:cargo-ant:1.4.15, org.apache.tomcat:catalina:6.0.26] on root project 't
emp'.
14:02:35.490 [ERROR] [org.gradle.BuildExceptionReporter]

_____
Ran the script with --stack trace : 
Build file 'C:\Users\sachin_dixit03\Desktop\temp\build.gradle' line: 29

* What went wrong:
A problem occurred evaluating root project 'temp'.
> Could not find method cargo() for arguments [org.codehaus.cargo:cargo-core-ube
rjar:1.4.15, org.codehaus.cargo:cargo-ant:1.4.15, org.apache.tomcat:catalina:6.0
.26] on root project 'temp'.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project
 'temp'.
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptR
unnerImpl.run(DefaultScriptRunnerFactory.java:76)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$
1.run(DefaultScriptPluginFactory.java:149)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.
apply(DefaultScriptPluginFactory.java:157)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildSc
riptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildSc
riptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.eva
luate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(L
ifecycleProjectEvaluator.java:55)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj
ect.java:488)
        at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProj
ect.java:86)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(Task
PathProjectEvaluator.java:42)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuil
dConfigurer.java:35)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLa
uncher.java:143)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:62)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:47)
        at org.gradle.initialization.DefaultGradleLauncher.runBuildOperation(Def
aultGradleLauncher.java:189)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:140)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGra
dleLauncher.java:35)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
eLauncher.java:104)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradl
eLauncher.java:97)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:62)
        at org.gradle.initialization.DefaultGradleLauncher.runRootBuildOperation
